version: "3.7"

services:
  mongo:
    image: jmeter-demo/mongo:5.0.5
    build:
      context: ./Dockerfiles/MongoDB/
      dockerfile: Dockerfile
    init: true
    restart: always
    volumes:
      - /data/db
      # - ./Dockerfiles/MongoDB:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PWD}
      MONGO_INITDB_USERNAME: mongo
      MONGO_INITDB_PASSWORD: ${USER_PWD}
    expose:
      - 27017
